### ISSUE TITLE
Camera Parameters Enquires

### ISSUE THREAD

**Issue by czha5168** [facebookresearch/VisualEchoes#4]
Hi Ruohan,

Thanks for providing this insightful dataset for visual-audio scene studies. I am working on SLAM studies and hence might need to know & adopt the camera parameters that you used to render this dataset. After a quick checking, I noticed this page from habitat-lab repo:https://github.com/facebookresearch/habitat-lab/blob/master/habitat_baselines/slambased/data/mp3d3_small1k.yaml, and would now like to make a quick confirmation with you when convenient - have you changed any camera settings yet (such as fx, fy, cx, and cy)? Best!!!

**Comment by rhgao** [comment]
Hi Chaoyi,

Thanks for your interest in our work. No, I didn’t change the camera settings, and I am using the default settings in habitat (also the same as what used in https://github.com/facebookresearch/sound-spaces <https://github.com/facebookresearch/sound-spaces>).

Best,
Ruohan
